// dashboard/src/pages/login.tsx
import { useState } from 'react';
import { useRouter } from 'next/router';
import { useAuth } from '../context/authContext';

export default function Login() {
  const { login } = useAuth();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isRegistering, setIsRegistering] = useState(false);
  const router = useRouter();

  const handleLogin = async () => {
    const credentials = btoa(`${username}:${password}`);

    const response = await fetch(`http://127.0.0.1:8000/user/login`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Basic ${credentials}`,
      },
    });

    if (response.ok) {
      localStorage.setItem('authToken', credentials);
      login();
      router.push('/');
    } else {
      alert('Login failed');
    }
  };

  const handleRegister = async () => {
    if (password !== confirmPassword) {
      alert('Passwords do not match');
      return;
    }

    const response = await fetch(`http://127.0.0.1:8000/user/create`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        username,
        password,
      }),
    });

    if (response.ok) {
      alert('Registration successful');
      setIsRegistering(false);
    } else {
      alert('Registration failed');
    }
  };

  const handleKeydown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter') {
      isRegistering ? handleRegister() : handleLogin();
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
        <h1 className="text-3xl font-bold mb-4 text-center">{isRegistering ? 'Register' : 'Login'}</h1>
        {isRegistering ? (
          <>
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              onKeyDown={handleKeydown}
              className="border rounded-lg p-2 mb-4 w-full"
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={handleKeydown}
              className="border rounded-lg p-2 mb-4 w-full"
            />
            <input
              type="password"
              placeholder="Confirm Password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              onKeyDown={handleKeydown}
              className="border rounded-lg p-2 mb-4 w-full"
            />
            <button
              onClick={handleRegister}
              className="px-4 py-2 bg-blue-500 text-white rounded-lg w-full hover:bg-blue-600 transition"
            >
              Register
            </button>
            <p className="mt-4 text-center text-gray-600">
              Already have an account?{' '}
              <span
                className="text-blue-500 cursor-pointer"
                onClick={() => setIsRegistering(false)}
              >
                Login
              </span>
            </p>
          </>
        ) : (
          <>
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              onKeyDown={handleKeydown}
              className="border rounded-lg p-2 mb-4 w-full"
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={handleKeydown}
              className="border rounded-lg p-2 mb-4 w-full"
            />
            <button
              onClick={handleLogin}
              className="px-4 py-2 bg-blue-500 text-white rounded-lg w-full hover:bg-blue-600 transition"
            >
              Login
            </button>
            <p className="mt-4 text-center text-gray-600">
              Don't have an account?{' '}
              <span
                className="text-blue-500 cursor-pointer"
                onClick={() => setIsRegistering(true)}
              >
                Register
              </span>
            </p>
          </>
        )}
      </div>
    </div>
  );
}

// dashboard/src/pages/Login.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  let username = "";
  let password = "";
  let confirmPassword = "";
  const dispatch = createEventDispatcher();
  let showRegister = false;

  async function login() {
    const formData = new FormData();
    formData.append("username", username);
    formData.append("password", password);

    const response = await fetch(`http://127.0.0.1:8000/token`, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({ username, password }),
    });

    if (response.ok) {
      const data = await response.json();
      localStorage.setItem("authToken", data.access_token);
      localStorage.setItem("username", username);
      localStorage.setItem("userid", data.userid)
      dispatch("loginSuccess");
    } else {
      alert("Login failed");
    }
  }

  async function register() {
    if (password !== confirmPassword) {
      alert("Passwords do not match");
      return;
    }

    const response = await fetch(`http://127.0.0.1:8000/user/create`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        username,
        password,
      }),
    });

    if (response.ok) {
      alert("Registration successful");
      showRegister = false;
    } else {
      alert("Registration failed");
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === "Enter") {
      if (showRegister) {
        register();
      } else {
        login();
      }
    }
  }
</script>

<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
    {#if showRegister}
      <h1 class="text-3xl font-bold mb-4 text-center">Register</h1>
      <input
        type="text"
        placeholder="Username"
        bind:value={username}
        on:keydown={handleKeydown}
        class="border rounded-lg p-2 mb-4 w-full"
      />
      <input
        type="password"
        placeholder="Password"
        bind:value={password}
        on:keydown={handleKeydown}
        class="border rounded-lg p-2 mb-4 w-full"
      />
      <input
        type="password"
        placeholder="Confirm Password"
        bind:value={confirmPassword}
        on:keydown={handleKeydown}
        class="border rounded-lg p-2 mb-4 w-full"
      />
      <button
        on:click={register}
        class="px-4 py-2 bg-green-500 text-white rounded-lg w-full hover:bg-green-600 transition"
        >Register</button
      >
      <div class="text-center mt-4">
        <button type="button" class="cursor-pointer text-blue-500 underline" on:click={() => showRegister = false}>Already have an account? Login here</button>
      </div>
    {:else}
      <h1 class="text-3xl font-bold mb-4 text-center">Login</h1>
      <input
        type="text"
        placeholder="Username"
        bind:value={username}
        on:keydown={handleKeydown}
        class="border rounded-lg p-2 mb-4 w-full"
      />
      <input
        type="password"
        placeholder="Password"
        bind:value={password}
        on:keydown={handleKeydown}
        class="border rounded-lg p-2 mb-4 w-full"
      />
      <button
        on:click={login}
        class="px-4 py-2 bg-blue-500 text-white rounded-lg w-full hover:bg-blue-600 transition"
        >Login
      </button>
      <div class="text-center mt-4">
        <button type="button" class="cursor-pointer text-blue-500 underline" on:click={() => showRegister = true}>Don't have an account? Register here</button>
      </div>
    {/if}
  </div>
</div>
