// dashboard/my-app/src/components/Sidebar.tsx
import Link from 'next/link';

export default function Sidebar() {
  return (
    <div className="w-64 h-screen bg-gray-800 text-white flex flex-col">
      <nav className="flex-grow">
        <ul className="space-y-2 p-4">
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/myai" className="block">MyAI</Link>
          </li>
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/secrets" className="block">Secrets</Link>
          </li>
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/analytics" className="block">Analytics</Link>
          </li>
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/billing" className="block">Billing</Link>
          </li>
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/account" className="block">Account</Link>
          </li>
          <li className="hover:bg-gray-700 p-2 rounded">
            <Link href="/settings" className="block">Settings</Link>
          </li>
        </ul>
      </nav>
      <div className="p-4">
        <button className="w-full bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded">Logout</button>
      </div>
    </div>
  );
}

// svelte-dashboard/src/components/Sidebar.svelte
<script lang="ts">
  import { Link, useLocation } from 'svelte-routing';
  import logo from '/llmproxyTransparent.png';
  
  // Get the current location
  const location = useLocation();

  // Reactive statement to track the current path
  $: currentPath = $location.pathname;
</script>

<div class="w-64 bg-white p-4 flex flex-col items-start border-r-2">
  <div class="w-full flex justify-center mb-6">
    <img src={logo} alt="Logo" class="w-28 h-28" />
  </div>
  <div class="font-semibold p-4 text-gray-400">MENU</div>
  <div class="flex flex-col justify-between space-y-2 w-full h-full">
    <div>
      <Link to="/secrets" class="w-full">
        <button
          class={`menu-item w-full h-12 p-2 rounded-lg flex items-center justify-start space-x-2 transition ${
            currentPath === '/secrets' ? 'bg-blue-100 text-blue-800' : 'text-gray-500 hover:bg-gray-200 hover:text-gray-700'
          }`}
          type="button"
        >
          <i class="icon-key"></i>
          <span class="font-semibold">Secrets</span>
        </button>
      </Link>
      <Link to="/analytics" class="w-full">
        <button
          class={`menu-item w-full h-12 p-2 rounded-lg flex items-center justify-start space-x-2 transition ${
            currentPath === '/analytics' ? 'bg-blue-100 text-blue-800' : 'text-gray-500 hover:bg-gray-200 hover:text-gray-700'
          }`}
          type="button"
        >
          <i class="icon-analytics"></i>
          <span class="font-semibold">Analytics</span>
        </button>
      </Link>
      <Link to="/billing" class="w-full">
        <button
          class={`menu-item w-full h-12 p-2 rounded-lg flex items-center justify-start space-x-2 transition ${
            currentPath === '/billing' ? 'bg-blue-100 text-blue-800' : 'text-gray-500 hover:bg-gray-200 hover:text-gray-700'
          }`}
          type="button"
        >
          <i class="icon-billing"></i>
          <span class="font-semibold">Billing</span>
        </button>
      </Link>
    </div>
    <div class="pb-8 pt-8 border-t-2">
      <Link to="/account" class="w-full">
        <button
          class={`menu-item w-full h-12 p-2 rounded-lg flex items-center justify-start space-x-2 transition ${
            currentPath === '/account' ? 'bg-blue-100 text-blue-800' : 'text-gray-500 hover:bg-gray-200 hover:text-gray-700'
          }`}
          type="button"
        >
          <i class="icon-account"></i>
          <span class="font-semibold">Account</span>
        </button>
      </Link>
      <Link to="/settings" class="w-full">
        <button
          class={`menu-item w-full h-12 p-2 rounded-lg flex items-center justify-start space-x-2 transition ${
            currentPath === '/settings' ? 'bg-blue-100 text-blue-800' : 'text-gray-500 hover:bg-gray-200 hover:text-gray-700'
          }`}
          type="button"
        >
          <i class="icon-settings"></i>
          <span class="font-semibold">Settings</span>
        </button>
      </Link>
    </div>
  </div>
</div>
